#!/bin/bash

var=$(($1/4+1))
for ((iter=1,i=1,j=2,k=3,l=4;iter<$var; ++iter,i+=4,j+=4,k+=4,l+=4)); 
do
    (/home/student/Downloads/OpenFace/build/bin/FaceLandmarkImg -f "$3/$2.$i.png" -ofdir "$3/datapoints") & 
    (/home/student/Downloads/OpenFace/build/bin/FaceLandmarkImg -f "$3/$2.$j.png" -ofdir "$3/datapoints") & 
    (/home/student/Downloads/OpenFace/build/bin/FaceLandmarkImg -f "$3/$2.$k.png" -ofdir "$3/datapoints") &
    (/home/student/Downloads/OpenFace/build/bin/FaceLandmarkImg -f "$3/$2.$l.png" -ofdir "$3/datapoints") &
    wait
done