#!/bin/bash
var=$(($1/4+4))
./eyeLike $3/$2.1.png > $3/test.txt
for ((iter=1,i=2,j=3,k=4,l=5;iter<$var; ++iter,i+=4,j+=4,k+=4,l+=4)); 
do
    (./eyeLike $3/$2.$i.png >> $3/test.txt) & 
    (./eyeLike $3/$2.$j.png >> $3/test.txt) & 
    (./eyeLike $3/$2.$k.png >> $3/test.txt) &
    (./eyeLike $3/$2.$l.png >> $3/test.txt) &
    wait
done