<?php
Echo "<ul>";
        Echo "<li><a href=AboutUs.php>About Us</a>";
        	Echo "<ul>";
       			Echo "<a href=AboutUs.php#Mission><li>Mission</li></a>";
                Echo "<a href=AboutUs.php#Leadership><li>Leadership</li></a>";
                Echo "<a href=AboutUs.php#Contact><li id=bottomNav>Contact Us</li></a>";
           Echo "</ul>";
       Echo "</li>";
        Echo "<li><a href=Partners.php>Partners</a>";
           	Echo "<ul>";
                Echo "<a href=Partners.php#Sponsors><li>Sponsors</li></a>";
                Echo "<a href=Partners.php#Other><li>Other Orgs</li></a>";
                Echo "<a href=Partners.php#Other><li class='bullet'><img src='images/roundDot.gif' />Silicon Valley Black Chamber of Commerce</li></a>";
                Echo "<a href=Partners.php#Other><li class='bullet'><img src='images/roundDot.gif' />African American Community Service Agency</li></a>";
                Echo "<a href=Partners.php#Other><li class='bullet'><img src='images/roundDot.gif' />Junior Achievement</li></a>";
                Echo "<a href=Partners.php#Other><li id=bottomNav class='bullet'><img src='images/roundDot.gif' />SV Grant Writers</li></a>";
            Echo "</ul>";
        Echo "</li>";
        Echo "<li><a href=Programs.php>Programs</a>";
             Echo "<ul>";
                Echo "<a href=Programs.php#NextGen><li>Next Gen Business Academy</li></a>";
                Echo "<a href=Programs.php#STEM><li>It Takes a Village with STEM</li></a>";
                Echo "<a href=Programs.php#Intern><li>Intern to Perm</li></a>";
                Echo "<a href=Programs.php#IncubatorProgram><li id=bottomNav>Small Business Incubator Program</li></a>";
            Echo "</ul>";
        Echo "</li>";
        Echo "<li><a href=Giving.php#Fundraisers>Events</a>";
            Echo "<ul>";
                Echo "<a href=http://blackchamber.com/BNBFundraiser/><li>Blacks n’ Business, Blacks n’ Technology Fundraiser</li></a>";
                Echo "<li id=bottomNav>S.V. Heritage Festival</li>";
           Echo "</ul>";
       Echo "</li>";
      Echo "<li><a href=Giving.php>Giving</a>";
            Echo "<ul>";
                Echo "<a href=Giving.php#Donations><li>Charitable Donations</li></a>";
                Echo "<a href=Giving.php#Fundraisers><li>Fundraisers</li></a>";
                Echo "<a href=Programs.php#NextGen><li id=bottomNav>Giving to Specific Programs</li></a>";
           Echo "</ul>";
      Echo "</li>";
   Echo "</ul>";
?>