<?php

Echo "<ul>";
            Echo "<li><a href=AboutUs.php>About Us</a>";
            	Echo "<ul>";
                  Echo "<a href=AboutUs.php#MissionGoals><li>Mission Goals</li></a>";
                  Echo "<a href=AboutUs.php#BoardOfDirectors><li>Board of Directors</li></a>";
                  Echo "<li>(e)Mobile Initiative</li>";
                  Echo "<a href=http://archive.constantcontact.com/fs110/1100850105922/archive/1119971362591.html><li>Newsletters</li></a>";
                  Echo "<a href=AboutUs.php#Videos><li>Videos</li></a>";
				  Echo "<a href=AboutUs.php#PressReleases><li>Press Releases</li></a>";
                  Echo "<a href=AboutUs.php#Contact><li id=bottomNav>Contact Us</li></a>";
                Echo "</ul>";
            Echo "</li>";
            Echo "<li><a href=Members.php>Members</a>";
           		  Echo "<ul>";
				  Echo "<a href=https://www.blackchambercommerce.org/membership.asp><li>Become a Member</li></a>"; 
				  Echo "<a href=Members.php#Benefits><li>Membership Benefits</li></a>"; 
                  Echo "<li>Free Mobile Subscribers</li>";
                  Echo "<li>Mobile Members</li>";
				  Echo "<a href=Members.php#Corporate><li>Corporate Members</li></a>";
				  Echo "<a href=Members.php#SmallBusiness><li>Small Bus Members</li></a>";
                  Echo "<a href=Members.php#Individuals><li>Individual Members</li></a>";   
				  Echo "<li>Member Testimonies</li>";
                  Echo "<a href=http://www.blackchambercommerce.org/busdirsearch.asp><li id=bottomNav>Online Business Directory</li></a>";
                 Echo "</ul>";
            Echo "</li>";
            Echo "<li><a href=Programs&Services.php>Programs</a>";
                Echo "<ul>";
                  Echo "<a href=Members.php#Sponsors><li>Sponsors</li></a>";
                  Echo "<a href=Programs&Services.php#NextGen><li>Next Generation Business Academy</li></a>";
                  Echo "<a href=Programs&Services.php#STEM><li>It Takes a Village with STEM</li></a>";
                  Echo "<a href=Programs&Services.php#Intern><li>Intern to Perm</li></a>";
                  Echo "<a href=Programs&Services.php#IncubatorProgram><li id=bottomNav>Incubator Program</li></a>";
                Echo "</ul>";
             Echo "</li>";
             Echo "<li><a href=Programs&Services.php#services>Services</a>";
             	Echo "<ul>";
         		  Echo "<a href=#IVQ><li>IVQ Next Gen Smart “Mobile Services”</li></a>";
                  Echo "<a href=Programs&Services.php#Workshops><li>Webinars, Workshops, Trainings</li></a>";
                  Echo "<a href=Programs&Services.php#Consulting><li>SBDC Consulting</li></a>";
                  Echo "<a href=Programs&Services.php#Finance><li>Financing Your Business</li></a>";
                  Echo "<a href=Programs&Services.php#Jobs><li id=bottomNav>Jobs / Contracts / Certifications</li></a>";
        		Echo "</ul>";
             Echo "</li>";
             Echo "<li>Mobilize";
            	Echo "<ul>";
                  Echo "<li>Sponsors: Local, Regional, National, Global</li>";
                  Echo "<li>IVQ Next Gen Smart “Mobile Services”</li>";
         		  Echo "<li>(e)Business Cards</li>";
                  Echo "<li>Moblie Coupons</li>";
                  Echo "<li>Group Messaging</li>";
                  Echo "<li>Member Services</li>";
                  Echo "<li>Member Directories</li>";
                  Echo "<li id=bottomNav>FREE Downloads</li>";
        		Echo "</ul>";
             Echo "</li>";
             Echo "<li><a href=Donating.php>Giving</a>";
             	Echo "<ul>";
         		  Echo "<a href=Donating.php#Donations><li>Charitable Donations</li></a>";
                  Echo "<a href=Programs&Services.php#NextGen><li>Giving to Specific Programs</li></a>";
				  Echo "<a href=Donating.php#Volunteer><li id=bottomNav>Volunteer Opportunities & Internships</li></a>";
        		Echo "</ul>";
             Echo "</li>";
			 Echo "<li><a href=radioshow/index.html>Radio Show</a></li>";
        Echo "</ul>";
?>